# Generated by Django 5.2.3 on 2025-07-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_unique_together_alter_booking_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityrule",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.staff",
            ),
            preserve_default=False,
        ),
    ]
