# Generated by Django 5.2.3 on 2025-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_availabilityrule_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="buffer_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
