# Generated by Django 5.2.3 on 2025-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_service_buffer_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
